[package]
name = "oxidize-pdf-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Command-line interface for oxidizePdf"
keywords = ["pdf", "cli", "command-line"]
categories = ["command-line-utilities"]

[[bin]]
name = "oxidizepdf"
path = "src/main.rs"

[dependencies]
# Core functionality
oxidize-pdf = { version = "0.1.2" }

# CLI
clap = { workspace = true }

# Error handling
anyhow = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Async runtime
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
pretty_assertions = { workspace = true }