# Test Suite Configuration

[general]
# Number of threads to use for parallel testing
test_threads = 4
# Timeout for individual tests (seconds)
test_timeout = 60
# Enable verbose output
verbose = false
# Save failed PDFs for debugging
save_failures = true
failure_dir = "test-failures"

[corpus]
# Paths to test fixtures
fixtures_dir = "fixtures"
# Categories to test
test_categories = [
    "Minimal",
    "Standard", 
    "Complex",
    "EdgeCases",
    "Corrupted",
    "Malformed"
]

[external_suites]
# Base directory for external test suites
base_dir = "external-suites"
# Enable external suite testing
enabled = true

[external_suites.vera_pdf]
# veraPDF corpus configuration
corpus_url = "https://github.com/veraPDF/veraPDF-corpus"
corpus_version = "master"
local_dir = "veraPDF-corpus"
test_pdfa = true
test_pdfua = true

[external_suites.qpdf]
# qpdf test suite configuration
repo_url = "https://github.com/qpdf/qpdf"
version = "main"
local_dir = "qpdf"
test_dirs = ["qtest/qpdf", "examples"]

[external_suites.isartor]
# Isartor test suite configuration
download_url = "https://www.pdfa.org/resource/isartor-test-suite/"
local_dir = "isartor"
include_negative = true

[validation]
# Strict mode - fail on any warning
strict_mode = false
# Check for PDF/A compliance
check_pdfa = true
# Check for accessibility (PDF/UA)
check_accessibility = false
# Maximum file size to test (MB)
max_file_size = 100

[benchmarks]
# Enable benchmark tests
enabled = true
# Number of iterations for benchmarks
iterations = 100
# Warm-up iterations
warmup_iterations = 10
# Save benchmark results
save_results = true
results_file = "benchmark-results.json"

[fuzzing]
# Fuzzing configuration
enabled = false
# Maximum input size for fuzzing
max_input_size = 10485760  # 10MB
# Number of fuzzing iterations
iterations = 10000
# Corpus directory for fuzzing
corpus_dir = "fuzz-corpus"

[reporting]
# Generate HTML report
html_report = true
# Generate JSON report for CI
json_report = true
# Include detailed error messages
detailed_errors = true
# Screenshot failed PDFs (requires external tool)
screenshot_failures = false