#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 GROFF_DEVPS_DIR OUTPUT_RS" >&2
    exit 2
fi

devps_dir=$1
output=$2

fonts=(HR HB HI HBI TR TB TI TBI CR CB CI CBI S ZD)
expected_hashes=(
    b2932b6db8f6dfae85e4ea66b3d2d649b2f2b572e07a5e9fda681e7c4ba1b146
    5511e30c25d0290721ad62783b4c588df224ff376c417a7f2058d6f778837d65
    17a5052eb25eecfbf8420a9d19c53ab629a13d63cfb4b7374666cc0f7ca80f5c
    82c6ddcbe8225093bc44aae8fc3b628d3bcef20086b2f976b1a89b3e9918f6bf
    7a78c01f4c5c7de12bcc60828918eafff97f7a79283ada49671e464f2dbb66ad
    5224fda02106f0342d7efdd6e7d3ddd2862e731feb7f941c51720820740aed73
    f40694b7976fb43f5a81ade43c19270cac2c668c158ed8bb4fd2a5888430c72d
    e778546984d794af2b59bab89d20bacbabb7d62b616a3e39e902b4d21f86f360
    e0bfd353a7be753a25dd22a9bb3f5ed0dcb45de1a3e2cb260fd4aa87fe02989f
    f4001361e5aca402592bbca830ccbc8d14b90556e30822eb91cb81c6ad7061e7
    d4b69cce24fbf30922dad977e5075f4efd68fcd92f4144fa86372ea07d6790d8
    68ae5e76957d578e4c651e06e696bbe701870db49b4a854720deb7cd75fe7f90
    8d307520c499e3dfde3206783cd85d2abf0c212bf4f2b61142f9f7656a626fa6
    a36a2f65cb521f8728640ae6a38b7587cb45c779184210595b7cc31d50d7bf61
)

hash_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{ print $1 }'
    else
        shasum -a 256 "$1" | awk '{ print $1 }'
    fi
}

for index in "${!fonts[@]}"; do
    source_file="$devps_dir/${fonts[$index]}"
    actual_hash=$(hash_file "$source_file")
    if [[ $actual_hash != "${expected_hashes[$index]}" ]]; then
        echo "unexpected metric source: $source_file ($actual_hash)" >&2
        exit 1
    fi
done

{
    echo '// @generated by scripts/generate_standard14_glyph_widths.sh.'
    echo '// Source: GNU groff 1.23.0 devps metrics generated from Adobe AFM 003.001.'
    echo '// Inputs are pinned by SHA-256 in the generator; Adobe metric data is used'
    echo '// under the notices preserved in the groff source files.'
    echo '// https://git.savannah.gnu.org/cgit/groff.git/tree/font/devps?h=1.23.0'
    echo '// Regenerate; do not hand-edit.'
    echo
    echo 'pub(super) fn glyph_width(font_name: &str, glyph_name: &str) -> Option<i32> {'
    echo '    match font_name {'
    for font_file in "${fonts[@]}"; do
        source_file="$devps_dir/$font_file"
        internal_name=$(awk '$1 == "internalname" { print $2; exit }' "$source_file")
        echo "        \"$internal_name\" => match glyph_name {"
        awk '
            $1 == "charset" { in_charset = 1; next }
            !in_charset || NF < 2 { next }
            {
                glyph = $NF
                split($2, metrics, ",")
                width = metrics[1]
                if (glyph !~ /^[A-Za-z0-9_.]+$/ || width !~ /^[0-9]+$/ || seen[glyph]++) next
                printf "            \"%s\" => Some(%s),\n", glyph, width
            }
        ' "$source_file"
        echo '            _ => None,'
        echo '        },'
    done
    echo '        _ => None,'
    echo '    }'
    echo '}'
} > "$output"
