#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 GROFF_DEVPS_DIR OUTPUT_RS" >&2
    exit 2
fi

devps_dir=$1
output=$2

fonts=(HR HB HI HBI TR TB TI TBI CR CB CI CBI S ZD)

{
    echo '// @generated by scripts/generate_standard14_glyph_widths.sh.'
    echo '// Source: Adobe AFM-derived GNU groff devps metrics (fonts version 003.001).'
    echo '// Regenerate; do not hand-edit.'
    echo
    echo 'pub(super) fn glyph_width(font_name: &str, glyph_name: &str) -> Option<i32> {'
    echo '    match font_name {'
    for font_file in "${fonts[@]}"; do
        source_file="$devps_dir/$font_file"
        internal_name=$(awk '$1 == "internalname" { print $2; exit }' "$source_file")
        echo "        \"$internal_name\" => match glyph_name {"
        awk '
            $1 == "charset" { in_charset = 1; next }
            !in_charset || NF < 2 { next }
            {
                glyph = $NF
                split($2, metrics, ",")
                width = metrics[1]
                if (glyph !~ /^[A-Za-z0-9_.]+$/ || width !~ /^[0-9]+$/ || seen[glyph]++) next
                printf "            \"%s\" => Some(%s),\n", glyph, width
            }
        ' "$source_file"
        echo '            _ => None,'
        echo '        },'
    done
    echo '        _ => None,'
    echo '    }'
    echo '}'
} > "$output"
