#!/usr/bin/env python3
"""Regenerate licensed CFF names/charsets using FontTools4.60.1 and read-fonts0.39.2.
Only data is copied. Usage: PYTHONPATH=<pinned-fonttools> python3 <script> <read-fonts-root>
"""
import argparse
from pathlib import Path
import re
import fontTools
from fontTools.cffLib import cffStandardStrings, cffIExpertStrings, cffExpertSubsetStrings
from fontTools.encodings.StandardEncoding import StandardEncoding

parser = argparse.ArgumentParser(__doc__)
parser.add_argument('fontations', type=Path)
args = parser.parse_args()
assert fontTools.__version__ == '4.60.1'
assert 'version = "0.39.2"' in (args.fontations / 'Cargo.toml').read_text()
root = Path(__file__).resolve().parents[1] / 'oxidize-pdf-core/src/text'
lines = ['//! Generated by tools/generate_intrinsic_font_names.py.',
         '//! Adobe CFF names/charsets: FontTools4.60.1; ExpertEncoding: read-fonts0.39.2.',
         '//! Licenses: font_program_licenses/{FONTTOOLS_LICENSE,FONTATIONS_LICENSE}.', '']
lines += [f'pub(super) const STANDARD_STRINGS: [&str; {len(cffStandardStrings)}] = [']
lines += [f'    "{name}",' for name in cffStandardStrings] + ['];', '']
for name, names in [('STANDARD_ENCODING', StandardEncoding), ('EXPERT_CHARSET', cffIExpertStrings), ('EXPERT_SUBSET_CHARSET', cffExpertSubsetStrings)]:
    values = [cffStandardStrings.index(value) for value in names]
    lines += [f'pub(super) const {name}: [u16; {len(values)}] = [']
    lines += ['    ' + ', '.join(map(str, values[start:start+16])) + ',' for start in range(0, len(values), 16)] + ['];', '']
source = (args.fontations / 'src/ps/encoding.rs').read_text()
match = re.search(r'pub\(super\) static EXPERT_ENCODING: \[u16; 256\] = \[.*?\];', source, re.S)
assert match
lines.append(match[0].replace('static', 'const'))
(root / 'font_program_names.rs').write_text('\n'.join(lines) + '\n')
