#!/usr/bin/env python3
"""Generate product CID→Unicode sequences from pinned Adobe PDF mappings.
Input: unchanged mapping-resources-pdf checkout/archive directory. Offline.
Independent from the representative #666 test-oracle sampler.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

REVISION = '2dd5e53fb74a01718b9dfd448a0d1cce6fff2aa5'
COLLECTIONS = [('Cns1', 'CNS1'), ('Gb1', 'GB1'), ('Japan1', 'Japan1'), ('Korea1', 'Korea1'), ('Kr', 'KR')]


LEGACY_API = """/// Legacy four-collection API. Use AdobeCidCollection for Adobe-KR support.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CidCollection {
    Cns1,
    Gb1,
    Japan1,
    Korea1,
}
impl CidCollection {
    pub fn from_ordering(ordering: &str) -> Option<Self> {
        match ordering {
            "CNS1" => Some(Self::Cns1),
            "GB1" => Some(Self::Gb1),
            "Japan1" => Some(Self::Japan1),
            "Korea1" => Some(Self::Korea1),
            _ => None,
        }
    }
    pub fn cid_to_unicode_sequence(&self, cid: u16) -> Option<&'static str> {
        AdobeCidCollection::from(*self).cid_to_unicode_sequence(cid)
    }
    pub fn cid_to_unicode(&self, cid: u16) -> Option<char> {
        AdobeCidCollection::from(*self).cid_to_unicode(cid)
    }
}
impl From<CidCollection> for AdobeCidCollection {
    fn from(collection: CidCollection) -> Self {
        match collection {
            CidCollection::Cns1 => Self::Cns1,
            CidCollection::Gb1 => Self::Gb1,
            CidCollection::Japan1 => Self::Japan1,
            CidCollection::Korea1 => Self::Korea1,
        }
    }
}
"""

def decode_mapping(source):
    mappings = {}
    for match in re.finditer(r'(\d+) beginbf(char|range)\s+(.*?)endbf\2', source, re.S):
        lines = [line.strip() for line in match[3].splitlines() if line.strip()]
        if len(lines) != int(match[1]):
            raise ValueError('mapping count mismatch')
        for line in lines:
            fields = re.fullmatch(r'<([0-9A-Fa-f]{4})>\s+(?:<([0-9A-Fa-f]{4})>\s+)?<([0-9A-Fa-f]+)>', line)
            if fields is None or (match[2] == 'range') != (fields[2] is not None):
                raise ValueError(f'unsupported mapping: {line}')
            start = int(fields[1], 16)
            end = int(fields[2], 16) if fields[2] else start
            destination = bytes.fromhex(fields[3])
            if start > end or not destination or len(destination) % 2:
                raise ValueError('invalid mapping range')
            for cid in range(start, end + 1):
                text = (int.from_bytes(destination, 'big') + cid - start).to_bytes(len(destination), 'big').decode('utf-16-be')
                if cid in mappings:
                    raise ValueError(f'duplicate CID {cid}')
                mappings[cid] = text
    if not mappings:
        raise ValueError('empty mapping')
    return mappings


def verify_sources(root):
    pins = json.loads(Path(__file__).with_name('adobe_cjk_source_pins.json').read_text())
    if pins['unicode_revision'] != REVISION:
        raise ValueError('source pin revision mismatch')
    for _, ordering in COLLECTIONS:
        relative = f'pdf2unicode/Adobe-{ordering}-UCS2'
        expected = pins['sources'][f'mapping-resources-pdf/{relative}']
        if hashlib.sha256((root / relative).read_bytes()).hexdigest() != expected:
            raise ValueError(f'source hash mismatch: {relative}')


def generate(root, output):
    verify_sources(root)
    lines = [f'// Generated by tools/generate_adobe_pdf_cid_tables.py; Adobe revision {REVISION}.',
             '// BSD-3-Clause; see cmap_resources/ADOBE-PDF-MAPPING-LICENSE.txt.',
             '#[derive(Debug, Clone, Copy, PartialEq, Eq)]', '#[non_exhaustive]', 'pub enum AdobeCidCollection {']
    lines.extend(f'    /// Adobe-{ordering} character collection.\n    {variant},' for variant, ordering in COLLECTIONS)
    lines += ['}', 'impl AdobeCidCollection {', '    pub fn from_ordering(ordering: &str) -> Option<Self> {', '        match ordering {']
    lines.extend(f'            "{ordering}" => Some(Self::{variant}),' for variant, ordering in COLLECTIONS)
    lines += ['            _ => None,', '        }', '    }',
              '    /// Complete PDF Unicode destination, including variation selectors.',
              '    /// CID 0 (.notdef) has no text in collection fallback; explicit ToUnicode wins.',
              "    pub fn cid_to_unicode_sequence(&self, cid: u16) -> Option<&'static str> {",
              '        if cid == 0 { return None; }',
              '        let table = match self {']
    lines.extend(f'            Self::{variant} => &{ordering.upper()}_CID_TO_UNICODE[..],' for variant, ordering in COLLECTIONS)
    lines += ['        };', '        table.binary_search_by_key(&cid, |entry| entry.0).ok().map(|i| table[i].1)', '    }',
              '    /// Scalar convenience API. Multi-scalar destinations return None.',
              '    pub fn cid_to_unicode(&self, cid: u16) -> Option<char> {',
              '        let mut chars = self.cid_to_unicode_sequence(cid)?.chars();',
              '        let first = chars.next()?;', '        chars.next().is_none().then_some(first)', '    }', '}', '']
    lines.append(LEGACY_API)
    provenance = {'revision': REVISION, 'sources': {}}
    for _, ordering in COLLECTIONS:
        file = root / 'pdf2unicode' / f'Adobe-{ordering}-UCS2'
        values = decode_mapping(file.read_text('ascii'))
        provenance['sources'][file.name] = {'sha256': hashlib.sha256(file.read_bytes()).hexdigest(), 'entries': len(values),
            'url': f'https://github.com/adobe-type-tools/mapping-resources-pdf/blob/{REVISION}/pdf2unicode/{file.name}'}
        lines += ['#[rustfmt::skip]', f'static {ordering.upper()}_CID_TO_UNICODE: [(u16, &str); {len(values)}] = [']
        for cid, value in sorted(values.items()):
            escaped = ''.join('\\u{' + format(ord(char), 'x') + '}' for char in value)
            lines.append(f'    ({cid}, "{escaped}"),')
        lines += ['];', '']
    output.write_text('\n'.join(lines))
    output.with_suffix('.provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument('root', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    generate(args.root, args.output)
