/// Integration tests for Issue #167: TextFlowContext::write_wrapped must respect
/// the cursor_x position set via `.at(x, y)` when computing the wrapping budget.
use oxidize_pdf::{Document, Font, Page, TextAlign};

/// Verifies the full round-trip: create a Document, place a TextFlowContext at
/// an x offset, write wrapped text, serialize to bytes, and assert:
///
/// 1. The output is a valid PDF (`%PDF-1.7` header).
/// 2. The generated operations contain Td x-coordinates >= 300, proving that
///    text does not wrap back to the left margin.
#[test]
fn test_text_wrapping_respects_at_x_position() {
    let mut doc = Document::new();
    let mut page = Page::new(612.0, 792.0);
    page.set_margins(50.0, 50.0, 50.0, 50.0);

    let mut text_flow = page.text_flow();

    // Place cursor at x=300; available width = 612 - 50 - 300 = 262pt.
    // Without the fix, write_wrapped used content_width (512pt) for the budget
    // and reset x to margins.left (50) on each line — causing overflow.
    text_flow
        .set_font(Font::Helvetica, 12.0)
        .set_alignment(TextAlign::Left)
        .at(300.0, 700.0)
        .write_wrapped(
            "This is a test of text that should wrap within the available width \
             when the cursor is positioned at an x offset via the at() method.",
        )
        .expect("write_wrapped should not fail");

    // Verify the generated operations before adding to page.
    // The operations string is plain text (not compressed at this stage).
    let ops = text_flow.operations().to_owned();

    // At least one Td operator must be present
    assert!(
        ops.contains(" Td"),
        "No Td operator found in operations:\n{ops}"
    );

    // Every Td x-coordinate must be >= 300 (the start_x we passed to .at())
    let mut td_found = false;
    for line in ops.lines() {
        if line.ends_with(" Td") {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 3 {
                if let Ok(x) = parts[0].parse::<f64>() {
                    td_found = true;
                    assert!(
                        x >= 300.0 - 1e-6,
                        "Td x-coordinate {x:.2} is less than start_x 300. \
                         Text wrapped back to the left margin — fix not applied.\n\
                         Operations:\n{ops}"
                    );
                }
            }
        }
    }
    assert!(
        td_found,
        "No parseable Td operators found in operations:\n{ops}"
    );

    // Also verify the document serializes to a valid PDF
    page.add_text_flow(&text_flow);
    doc.add_page(page);

    let bytes = doc.to_bytes().expect("to_bytes should not fail");
    assert!(
        bytes.starts_with(b"%PDF-1.7"),
        "Generated bytes should start with %PDF-1.7 header"
    );
    assert!(bytes.len() > 100, "PDF should have meaningful content");
}
