name: Create Benchmark Baseline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create baseline from'
        required: false
        type: string
        default: 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-baseline:
    name: Create Benchmark Baseline
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build release binary
      run: cargo build --release --bin oxidizepdf
      
    - name: Run all benchmarks
      run: |
        echo "Running core benchmarks..."
        cargo bench --package oxidize-pdf-test-suite --bench core_benchmarks
        
        echo "Running parser benchmarks..."
        cargo bench --package oxidize-pdf-test-suite --bench parser_bench
        
        echo "Running memory benchmarks..."
        cargo bench --package oxidize-pdf-test-suite --bench memory_benchmarks
        
        echo "Running CLI benchmarks..."
        cargo bench --package oxidize-pdf-test-suite --bench cli_benchmarks
        
    - name: Create baseline directory
      run: |
        # Create temporary directory to preserve files across checkout
        mkdir -p /tmp/baseline
        cp -r target/criterion/* /tmp/baseline/
        echo "Baseline created from branch: ${{ github.event.inputs.branch }}" > /tmp/baseline/info.txt
        echo "Date: $(date)" >> /tmp/baseline/info.txt
        echo "Commit: $(git rev-parse HEAD)" >> /tmp/baseline/info.txt
        
    - name: Commit baseline
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Fetch and checkout the benchmark-baselines branch
        git fetch origin benchmark-baselines:benchmark-baselines || git checkout -b benchmark-baselines
        git checkout benchmark-baselines
        
        # Copy baseline files
        mkdir -p .github/benchmarks/baseline
        cp -r /tmp/baseline/* .github/benchmarks/baseline/ 2>/dev/null || true
        
        git add .github/benchmarks/baseline
        git commit -m "chore: create benchmark baseline from ${{ github.event.inputs.branch }}
        
        Baseline created for performance comparison
        Branch: ${{ github.event.inputs.branch }}
        Commit: $(git rev-parse HEAD)" || echo "No changes to commit"
        git push origin benchmark-baselines
        
    - name: Upload baseline artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-baseline
        path: .github/benchmarks/baseline/