name: ISO Compliance Tests

on:
  push:
    branches: [ main, develop, develop_santi ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly to catch regressions
    - cron: '0 0 * * 0'

jobs:
  compliance-test:
    name: Run ISO 32000 Compliance Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run API Verification Test
      run: |
        cd test-suite
        cargo test --test api_verification_simple -- --nocapture
      continue-on-error: true
    
    - name: Run Pragmatic Compliance Test
      run: |
        cd test-suite
        cargo test --test iso_compliance_pragmatic -- --nocapture
      continue-on-error: true
    
    - name: Run Comprehensive Compliance Test
      run: |
        cd test-suite
        cargo test --test iso_compliance_comprehensive -- --nocapture | tee compliance_output.txt
    
    - name: Extract Compliance Percentage
      id: compliance
      run: |
        COMPLIANCE=$(grep "Overall REAL Compliance:" test-suite/compliance_output.txt | grep -oE '[0-9]+\.[0-9]+%' | head -1)
        echo "percentage=$COMPLIANCE" >> $GITHUB_OUTPUT
        echo "ISO 32000 Compliance: $COMPLIANCE"
    
    - name: Upload Compliance Reports
      uses: actions/upload-artifact@v3
      with:
        name: compliance-reports
        path: |
          test-suite/ISO_COMPLIANCE_HONEST_REPORT.md
          test-suite/API_DISCREPANCIES.md
          test-suite/REAL_COMPLIANCE_STATUS.md
    
    - name: Comment PR with Compliance
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const compliance = '${{ steps.compliance.outputs.percentage }}';
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## ISO 32000 Compliance Check\n\n**Current compliance: ${compliance}**\n\nSee artifacts for detailed reports.`
          })
    
    - name: Create Compliance Badge
      run: |
        COMPLIANCE=${{ steps.compliance.outputs.percentage }}
        echo "ISO 32000 Compliance: $COMPLIANCE" > compliance_badge.txt
    
    - name: Check Compliance Regression
      run: |
        # Fail if compliance drops below 17%
        COMPLIANCE=$(echo "${{ steps.compliance.outputs.percentage }}" | tr -d '%')
        if (( $(echo "$COMPLIANCE < 17" | bc -l) )); then
          echo "ERROR: Compliance dropped below 17%!"
          exit 1
        fi