name: Code Coverage

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tesseract OCR and PDF tools
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage
        run: |
          cargo tarpaulin \
            -p oxidize-pdf \
            --out Xml \
            --timeout 1200 \
            --release \
            --exclude-files "**/tests/**" \
            --exclude-files "**/examples/**" \
            --exclude-files "**/benches/**" \
            --exclude-files "tests/**" \
            --exclude-files "examples/**" \
            --exclude-files "benches/**" \
            --exclude-files "tools/**" \
            --exclude-files "dev-tools/**" \
            --run-types Lib \
            --skip-clean \
            --ignore-panics \
            --avoid-cfg-tarpaulin
        timeout-minutes: 45

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          flags: unittests
          name: codecov-umbrella
